# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AWSome Hacks
description: > # this means to ignore newlines until "baseurl:"
 This website is used to write technical blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.techpointcloud.com"
permalink: :title/
full-url: "http://blog.techpointcloud.com/" # the base hostname & protocol for your site

# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname: awscloudhacks

# Tracker
analytics: UA-83979019-1

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token: 57745490983a8a31c746b433b68043ea

# Redirect users after submitting the form
redirect-to: http://blog.techpointcloud.com

# Site version
version: 0.9


# Post date background - This will change the background of the post date and tag ribbon according to the theme. If set to no default green background will be used. If yes then the theme color scheme is used.

change-date-bg: no


# Build settings
markdown: kramdown

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: Senthil
  image: ashwat.jpg # The author image will be shown on the header. Place this image in /images/ folder.
  about: Who is eager to learn new technology
  twitter: senthil  # https://twitter.com/ is automatically added
  facebook: senthil # https://facebook.com/ is automatically added
  email: awscloudhacks@gmail.com # mailto: is automatically added
  
gems: 
  - jekyll-seo-tag
  - jekyll-paginate

#Test commit